RP_PARAMETERS:
  learning_starts: 1
  batch_size: 1
  train_freq: 1
  predictor_epochs: 4
  lr: 0.0001
  

ENV_PARAMETERS:
  num_frames: 2
  num_agent: 7
  ep_length: 600
  num_envs: 4
  num_cpus: 1

RL_PARAMETERS:
  learner: "dqn"
  spawn_speed: "slow"
  learning_rate: 0.00025
  batch_size: 32
  tau: 0.01
  gamma: 0.99
  train_freq: 4
  exploration_fraction: 0.3
  learning_starts: 500000
  buffer_size: 700
  exploration_final_eps: 0.1
  policy: CnnPolicy
  render_frequency: 20

EXPERIMENT_PARAMETERS:
  penalty: False
  metric: "Efficiency"
  experiment: "crm"
  independent: False 
  run_name_template: "{experiment}-{metric}-{spawn_speed}-{num_agents}_agents"
  gpu_id: 0
  debug: False
  total_timesteps: 35_000
    