
MEDIUM_HARVEST_MAP = [
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    '@P A P   A    A    A    A  A    A    @',
    '@  AAA  AAA  AAA  AAA  AAAAAA  AAA   @',
    '@ A A    A    A    A    A  A    A   P@',
    '@PA             A      A       A     @',
    '@ A   A    A    A    A  A A  A    A  @',
    '@PAA AAA  AAA  AAA  AAA     AAA  AAA @',
    '@ A   A    A  A A  A A   P   A    A  @',
    '@PA                                P @',
    '@ A    A    A    A    A  A    A    A @',
    '@AAA  AAA  AAA  AAA  AA AAA  AAA  AA @',
    '@ A    A    A    A    A  A    A    A @',
    '@P A A A               P             @',
    '@P  A    A    A    A       P     P   @',
    '@  AAA  AAA  AAA  AAA         P    P @',
    '@P  A    A    A    A   P   P  P  P   @',
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@', ]

SMALL_HARVEST_MAP = [
    '@@@@@@@@@@@@@@@@@@@@@@@@@@',
    '@P A    A    A    A  P AP@',
    '@PAAA  AAA  AAA  AAA  AAA@',
    '@  A    A    A    A    A @',
    '@P                       @',
    '@    A    A    A    A    @',
    '@   AAA  AAA  AAA  AAA   @',
    '@P P A    A    A    A P P@',
    '@@@@@@@@@@@@@@@@@@@@@@@@@@', ]

MEDIUM2_HARVEST_MAP = [
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@  P     A P AA    P    AAA@",
    "@P    A AAA  AAA    A    A @",
    "@ A  AAA A    A  A AAA  A  @",
    "@AAA  A A    A  AAA A  AAA @",
    "@ P  A       A  A AAA    A @",
    "@A  AAA  A  A  AAA A    AAA@",
    "@    A A   AAA  A A      A @",
    "@P    AAA   A A  AAA      A@",
    "@ A    A     AAA  A  P     @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
]


HARVEST_MAP = [
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@ P   P      A    P AAAAA    P  A P  @",
    "@  P     A P AA    P    AAA    A  A  @",
    "@     A AAA  AAA    A    A AA AAAA   @",
    "@ A  AAA A    A  A AAA  A  A   A A   @",
    "@AAA  A A    A  AAA A  AAA        A P@",
    "@ A A  AAA  AAA  A A    A AA   AA AA @",
    "@  A A  AAA    A A  AAA    AAA  A    @",
    "@   AAA  A      AAA  A    AAAA       @",
    "@ P  A       A  A AAA    A  A      P @",
    "@A  AAA  A  A  AAA A    AAAA     P   @",
    "@    A A   AAA  A A      A AA   A  P @",
    "@     AAA   A A  AAA      AA   AAA P @",
    "@ A    A     AAA  A  P          A    @",
    "@       P     A         P  P P     P @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
]

HARVEST_MAP_LARGER = [
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@ P   P      A    P AAAAA    P  A P     A  P      P @",
    "@  P     A P AA    P    AAA    A  A       A   P     @",
    "@     A AAA  AAA    A    A AA AAAA      AAA    A    @",
    "@ A  AAA A    A  A AAA  A  A   A A   AAA    AA      @",
    "@AAA  A A    A  AAA A  AAA        A P  A AA   AAA P @",
    "@ A A  AAA  AAA  A A    A AA   AA AA   A  AA A  A   @",
    "@  A A  AAA    A A  AAA    AAA  A      AA    AAA    @",
    "@   AAA  A      AAA  A    AAAA      AAAA     A      @",
    "@ P  A       A  A AAA    A  A      P  A       A P   @",
    "@A  AAA  A  A  AAA A    AAAA     P    AAA   A       @",
    "@    A A   AAA  A A      A AA   A  P     A   A    P @",
    "@     AAA   A A  AAA      AA   AAA P   AA  AA  AA   @",
    "@ A    A     AAA  A  P          A       A    A      @",
    "@ P     A    A       AAA   P         P P  P    P    @",
    "@     A A  AA  A  A  AAA       A     A      A   AAA @",
    "@ P  AAA   A AA  A      A      AAA A  A  AA A       @",
    "@  A AA     A   AA   AAA  P    AAAA      AAA    A   @",
    "@     A AAAA   A   A    AAAA      A  AA     A  A    @",
    "@A   AAA  A   A  AAA    A     P AAA   A  P A        @",
    "@ A      A  A   AAA       A    A    P  A      P     @",
    "@ P     A    P   A  P      P   A       P     A      @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
]



ARIGINALHARVEST_MAP_LARGER = [
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    '@PPPPPPP     A      AAAAA           A    @',
    '@PPPPP   A   AA         AAA        A  A  @',
    '@PPP  A AAA  AAA    A    A  A AAA AAAA   @',
    '@ A  AAA A    A  A AAA  A  AAA A   A A   @',
    '@AAA  A A    A  AAA A  AAA  A A       A  @',
    '@ A A  AAA  AAA  A A    A A  AAA   AA AA @',
    '@  AAA  A    A A  AAA    AAA  A     AAA  @',
    '@   A         AAA  A      A          A   @',
    '@  AAA    A    A               A    AAA  @',
    '@   A  A AAA    A  A AAA      A  AAA A   @',
    '@  A  AAA A    A  AAA A      AAA  A A    @',
    '@ AAA  A A    AAA  A A        A A  AAA   @',
    '@  A A  AAA    A A  AAA        AAA  A    @',
    '@   AAA  A      AAA  A    A  A AAA       @',
    '@    A       A  A AAA    A  AAA A        @',
    '@A  AAA  A  A  AAA A    AAA  A A    PPPPP@',
    '@    A A   AAA  A A      A A  AAA  pPPPPP@',
    '@     AAA   A A  AAA      AAA PA PPPPPPPP@',
    '@ A    A     AAA  A        A  PPPPPPPPPPP@',
    '@             A            PPPPPPPPPPPPPP@',
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
    ]